name:                BillingPanda
version:             0.1.0.0
github:              "frankwang0/BillingPanda"
license:             BSD3
author:              "Frank Wang"
maintainer:          "frankwangsydney@gmail.com"
copyright:           "2019 Frank Wang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/frankwang0/BillingPanda#readme>

dependencies:
  - base
  - classy-prelude
  # - pcre-heavy
  - mtl
  - data-has
  - string-random
  - resource-pool
  - postgresql-simple
  - postgresql-simple-migration 
  - time

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ConstraintKinds
  - FlexibleContexts
  - GeneralizedNewtypeDeriving


library:
  source-dirs: src

executables:
  BillingPanda-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BillingPanda

tests:
  BillingPanda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BillingPanda
